/**
 * Tailwind config (Stage Prepare). theme.extend мапится на design-токены `--ds-*`
 * (src/styles/theme.css ← remote Figma-библиотека). На этапе Styles сюда добавляются новые токены.
 * preflight выключен: Tailwind даёт только утилиты, не переопределяя CSS существующих компонентов
 * (см. DECISIONS D29).
 */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx,js,jsx,mdx}'],
  darkMode: 'class',
  corePlugins: { preflight: false },
  theme: {
    extend: {
      colors: {
        black: 'var(--ds-color-black)',
        white: 'var(--ds-color-white)',
        'text-primary': 'var(--ds-color-text-primary)',
        'text-secondary': 'var(--ds-color-text-secondary)',
        'text-on-color': 'var(--ds-color-text-on-color)',
        'text-green': 'var(--ds-color-text-green)',
        'text-brown': 'var(--ds-color-text-brown)',
        'control-secondary': 'var(--ds-color-control-secondary)',
        'control-on-color': 'var(--ds-color-control-on-color)',
        'control-brown': 'var(--ds-color-control-brown)',
        'bg-base': 'var(--ds-color-bg-base)',
        lines: 'var(--ds-color-lines)',
        gray: 'var(--ds-color-gray)',
        'super-yellow': 'var(--ds-color-super-yellow)',
        'card-white': 'var(--ds-color-card-white)',
        'card-red': 'var(--ds-color-card-red)',
        'card-pink': 'var(--ds-color-card-pink)',
        'card-lavender': 'var(--ds-color-card-lavender)',
        'card-olive': 'var(--ds-color-card-olive)',
        'card-green': 'var(--ds-color-card-green)',
        'card-peach': 'var(--ds-color-card-peach)',
        'oncard-red': 'var(--ds-color-oncard-red)',
        'oncard-green': 'var(--ds-color-oncard-green)',
        'oncard-yellow': 'var(--ds-color-oncard-yellow)',
        'bar-filled': 'var(--ds-color-bar-filled)',
        'bar-empty': 'var(--ds-color-bar-empty)',
        'tech-purple': 'var(--ds-color-tech-purple)',
        'tech-green': 'var(--ds-color-tech-green)',
        'tech-red': 'var(--ds-color-tech-red)',
        'tech-gray': 'var(--ds-color-tech-gray)',
        accent: 'var(--ds-color-accent)',
      },
      fontFamily: {
        sans: ['var(--ds-font-family)'],
        display: ['var(--ds-font-family-display)'],
        pixel: ['var(--ds-font-family-pixel)'],
      },
      fontWeight: {
        regular: 'var(--ds-font-weight-regular)',
        medium: 'var(--ds-font-weight-medium)',
      },
      fontSize: {
        caps: 'var(--ds-font-size-caps)',
        'text-gr': 'var(--ds-font-size-text-gr)',
        m: 'var(--ds-font-size-m)',
        h3: 'var(--ds-font-size-h3)',
        description: 'var(--ds-font-size-description)',
        h1: 'var(--ds-font-size-h1)',
      },
      spacing: {
        'ds-xxxs': 'var(--ds-indent-xxxs)',
        'ds-xxs': 'var(--ds-indent-xxs)',
        'ds-xs': 'var(--ds-indent-xs)',
        'ds-s': 'var(--ds-indent-s)',
        'ds-m': 'var(--ds-indent-m)',
        'ds-l': 'var(--ds-indent-l)',
        'ds-xl': 'var(--ds-indent-xl)',
        'ds-xxl': 'var(--ds-indent-xxl)',
        'ds-neg-1': 'var(--ds-indent-neg-1)',
        'ds-neg-xs': 'var(--ds-indent-neg-xs)',
      },
      borderRadius: {
        s: 'var(--ds-radius-s)',
        m: 'var(--ds-radius-m)',
        l: 'var(--ds-radius-l)',
        over: 'var(--ds-radius-over)',
      },
      letterSpacing: { caps: 'var(--ds-letter-spacing-caps)' },
      maxWidth: { 'ds-base': 'var(--ds-size-base-width)' },
      transitionDuration: { ds: '160ms' },
      transitionTimingFunction: { ds: 'cubic-bezier(0.4, 0, 0.2, 1)' },
      boxShadow: {
        'ds-1': 'var(--ds-shadow-1)',
        'ds-2': 'var(--ds-shadow-2)',
        'ds-3': 'var(--ds-shadow-3)',
      },
      ringColor: { focus: 'var(--ds-color-focus)' },
    },
  },
  plugins: [],
}
